// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PV260.ArkFundsTracker.Web.Infrastructure.Data;

#nullable disable

namespace PV260.ArkFundsTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416194127_FreshMigration")]
    partial class FreshMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PV260.ArkFundsTracker.Web.Slices.FundPosition.FundPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cusip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fund")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ARKK");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("idx_fund_positions_ticker");

                    b.ToTable("fund_positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_fund_positions_fund", "\"Fund\" = 'ARKK'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00ba0e09-9fa6-41d1-8b63-1151ffae91f6"),
                            Company = "ROBINHOOD MARKETS INC - A",
                            Cusip = "770700102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 305435219.2m,
                            Shares = 3861869m,
                            Ticker = "HOOD",
                            WeightPercentage = 4.57m
                        },
                        new
                        {
                            Id = new Guid("02c6c154-91e7-432b-bfa3-2e11cd096471"),
                            Company = "TAIWAN SEMICONDUCTOR-SP ADR",
                            Cusip = "874039100",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 94165233.75m,
                            Shares = 247875m,
                            Ticker = "TSM",
                            WeightPercentage = 1.41m
                        },
                        new
                        {
                            Id = new Guid("0c50e251-bb9e-447f-b657-7fa696fe74bf"),
                            Company = "CIRCLE INTERNET GROUP INC",
                            Cusip = "172573107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 302123465.5m,
                            Shares = 2864001m,
                            Ticker = "CRCL",
                            WeightPercentage = 4.52m
                        },
                        new
                        {
                            Id = new Guid("0d4ed431-525c-4559-a8ae-2414e1959568"),
                            Company = "KRATOS DEFENSE & SECURITY",
                            Cusip = "50077B207",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 61570994.46m,
                            Shares = 835881m,
                            Ticker = "KTOS",
                            WeightPercentage = 0.92m
                        },
                        new
                        {
                            Id = new Guid("15f402ee-3277-4a78-8947-d9e53ed22fbf"),
                            Company = "CRISPR THERAPEUTICS AG",
                            Cusip = "H17182108",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 448943702.3m,
                            Shares = 7895598m,
                            Ticker = "CRSP",
                            WeightPercentage = 6.71m
                        },
                        new
                        {
                            Id = new Guid("186f8e3d-d0c7-4d3b-9410-9f346324f150"),
                            Company = "BRERA HOLDINGS PLC-CL B",
                            Cusip = "G13311116",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 5618583.6m,
                            Shares = 6688790m,
                            Ticker = "SLMT",
                            WeightPercentage = 0.08m
                        },
                        new
                        {
                            Id = new Guid("19b8e63b-c8e4-418e-9493-b8670c681ff2"),
                            Company = "ARCHER AVIATION INC-A",
                            Cusip = "03945R102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 103952050.7m,
                            Shares = 18333695m,
                            Ticker = "ACHR",
                            WeightPercentage = 1.55m
                        },
                        new
                        {
                            Id = new Guid("1b78ca9d-1d76-4faa-a230-2312f6a4094a"),
                            Company = "BROADCOM INC",
                            Cusip = "11135F101",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 71965896.88m,
                            Shares = 188996m,
                            Ticker = "AVGO",
                            WeightPercentage = 1.08m
                        },
                        new
                        {
                            Id = new Guid("1fe60f8c-26db-4f05-a189-e5fc07ac6ff4"),
                            Company = "ILLUMINA INC",
                            Cusip = "452327109",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 83645892m,
                            Shares = 641850m,
                            Ticker = "ILMN",
                            WeightPercentage = 1.25m
                        },
                        new
                        {
                            Id = new Guid("2064cf21-c0e0-48b8-8320-83e6fc857856"),
                            Company = "TWIST BIOSCIENCE CORP",
                            Cusip = "90184D100",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 202929366m,
                            Shares = 3534739m,
                            Ticker = "TWST",
                            WeightPercentage = 3.03m
                        },
                        new
                        {
                            Id = new Guid("2f19cbb7-1ec8-4a94-8892-5ccadf2a1677"),
                            Company = "COINBASE GLOBAL INC -CLASS A",
                            Cusip = "19260Q107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 281531186.2m,
                            Shares = 1526659m,
                            Ticker = "COIN",
                            WeightPercentage = 4.21m
                        },
                        new
                        {
                            Id = new Guid("30f446a0-e44f-406f-a53d-3bee85c3c752"),
                            Company = "BULLISH",
                            Cusip = "G16910120",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 169387756m,
                            Shares = 4170058m,
                            Ticker = "BLSH",
                            WeightPercentage = 2.53m
                        },
                        new
                        {
                            Id = new Guid("310dc826-a1d1-4990-8c73-7de6f05bc334"),
                            Company = "VERACYTE INC",
                            Cusip = "92337F107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 63087921.4m,
                            Shares = 1839298m,
                            Ticker = "VCYT",
                            WeightPercentage = 0.94m
                        },
                        new
                        {
                            Id = new Guid("32de7ab3-ecc2-40cc-b560-88561b37a2bc"),
                            Company = "DEERE & CO",
                            Cusip = "244199105",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 83365730.64m,
                            Shares = 139866m,
                            Ticker = "DE",
                            WeightPercentage = 1.25m
                        },
                        new
                        {
                            Id = new Guid("35538618-53d5-405f-bd4c-1bb26a5f6ae7"),
                            Company = "BWX TECHNOLOGIES INC",
                            Cusip = "05605H100",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 74812729.41m,
                            Shares = 313983m,
                            Ticker = "BWXT",
                            WeightPercentage = 1.12m
                        },
                        new
                        {
                            Id = new Guid("37044bae-49b2-48f8-ae22-50b5e44bb7c8"),
                            Company = "SOFI TECHNOLOGIES INC",
                            Cusip = "83406F102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 40733501.04m,
                            Shares = 2274344m,
                            Ticker = "SOFI",
                            WeightPercentage = 0.61m
                        },
                        new
                        {
                            Id = new Guid("531586c8-2fd3-4178-b7ac-e53f91cb9e99"),
                            Company = "GENEDX HOLDINGS CORP",
                            Cusip = "81663L200",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 58072322.76m,
                            Shares = 868566m,
                            Ticker = "WGS",
                            WeightPercentage = 0.87m
                        },
                        new
                        {
                            Id = new Guid("541c9aae-1f39-47a3-9c34-6aa089de56f9"),
                            Company = "FIGMA INC-CL A",
                            Cusip = "316841105",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 33762312.72m,
                            Shares = 1832916m,
                            Ticker = "",
                            WeightPercentage = 0.5m
                        },
                        new
                        {
                            Id = new Guid("5a0cc849-256f-4aac-8201-26cd06755fe9"),
                            Company = "BAIDU INC - SPON ADR",
                            Cusip = "56752108",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 65506395.57m,
                            Shares = 554059m,
                            Ticker = "BIDU",
                            WeightPercentage = 0.98m
                        },
                        new
                        {
                            Id = new Guid("5a7e4695-80fb-4554-9350-93753b2fcf6a"),
                            Company = "PALANTIR TECHNOLOGIES INC-A",
                            Cusip = "69608A108",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 207008857.3m,
                            Shares = 1525489m,
                            Ticker = "PLTR",
                            WeightPercentage = 3.09m
                        },
                        new
                        {
                            Id = new Guid("5f2c0ff4-43fe-4a38-ac9c-50393c8594aa"),
                            Company = "CERUS CORP",
                            Cusip = "157085101",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 20253561.99m,
                            Shares = 10076399m,
                            Ticker = "CERS",
                            WeightPercentage = 0.3m
                        },
                        new
                        {
                            Id = new Guid("61bff91c-b981-44a6-83c7-9a04df9746a0"),
                            Company = "10X GENOMICS INC-CLASS A",
                            Cusip = "88025U109",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 175880682.4m,
                            Shares = 7091963m,
                            Ticker = "TXG",
                            WeightPercentage = 2.63m
                        },
                        new
                        {
                            Id = new Guid("76307d70-1af7-45ac-97fc-7d79002a7870"),
                            Company = "COREWEAVE INC-CL A",
                            Cusip = "21873S108",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 187053895.6m,
                            Shares = 1596023m,
                            Ticker = "CRWV",
                            WeightPercentage = 2.8m
                        },
                        new
                        {
                            Id = new Guid("7b1c662f-c47e-47a3-8be5-200839472f03"),
                            Company = "NATERA INC",
                            Cusip = "632307104",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 82842239.76m,
                            Shares = 385959m,
                            Ticker = "NTRA",
                            WeightPercentage = 1.24m
                        },
                        new
                        {
                            Id = new Guid("7c42e6d3-80ce-483f-84f3-9fa39a367074"),
                            Company = "ROBLOX CORP -CLASS A",
                            Cusip = "771049103",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 219743602.1m,
                            Shares = 3769187m,
                            Ticker = "RBLX",
                            WeightPercentage = 3.28m
                        },
                        new
                        {
                            Id = new Guid("816f1bd2-9e82-4cae-91e2-a836f2cef2a6"),
                            Company = "NVIDIA CORP",
                            Cusip = "67066G104",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 79218486.77m,
                            Shares = 403127m,
                            Ticker = "NVDA",
                            WeightPercentage = 1.18m
                        },
                        new
                        {
                            Id = new Guid("8c364f18-4f19-479c-80bc-d99eda640bca"),
                            Company = "ADVANCED MICRO DEVICES",
                            Cusip = "7903107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 294280635.8m,
                            Shares = 1153725m,
                            Ticker = "AMD",
                            WeightPercentage = 4.4m
                        },
                        new
                        {
                            Id = new Guid("933eec18-d24a-4393-b17c-455c9b2758cc"),
                            Company = "AMAZON.COM INC",
                            Cusip = "23135106",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 149175680m,
                            Shares = 599051m,
                            Ticker = "AMZN",
                            WeightPercentage = 2.23m
                        },
                        new
                        {
                            Id = new Guid("966ee5eb-cac2-485f-8582-9b2b67fafcd5"),
                            Company = "ALPHABET INC-CL C",
                            Cusip = "02079K107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 58306047.5m,
                            Shares = 176375m,
                            Ticker = "GOOG",
                            WeightPercentage = 0.87m
                        },
                        new
                        {
                            Id = new Guid("9e3200d3-a35b-45fd-bdd8-3782ff10169d"),
                            Company = "BRERA HOLDINGS PLC WTS",
                            Cusip = "BREADUMMY",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 2373941.35m,
                            Shares = 4316257m,
                            Ticker = "",
                            WeightPercentage = 0.04m
                        },
                        new
                        {
                            Id = new Guid("a02defa6-70da-418e-8c8e-c334fb907267"),
                            Company = "ALIBABA GROUP HOLDING-SP ADR",
                            Cusip = "01609W102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 61969879.2m,
                            Shares = 471792m,
                            Ticker = "BABA",
                            WeightPercentage = 0.93m
                        },
                        new
                        {
                            Id = new Guid("a9225ef6-5286-4783-81eb-50f01a8a1550"),
                            Company = "TERADYNE INC",
                            Cusip = "880770102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 140858781.8m,
                            Shares = 385376m,
                            Ticker = "TER",
                            WeightPercentage = 2.11m
                        },
                        new
                        {
                            Id = new Guid("b072f570-ef89-4c97-93d7-f39644ffae12"),
                            Company = "GOLDMAN FS TRSY OBLIG INST 468",
                            Cusip = "X9USDGSFT",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 4425986.19m,
                            Shares = 4425986m,
                            Ticker = "",
                            WeightPercentage = 0.07m
                        },
                        new
                        {
                            Id = new Guid("b269d881-afeb-40a0-9e33-a42214d1be95"),
                            Company = "META PLATFORMS INC-CLASS A",
                            Cusip = "30303M102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 25571451.51m,
                            Shares = 38599m,
                            Ticker = "META",
                            WeightPercentage = 0.38m
                        },
                        new
                        {
                            Id = new Guid("b9a4167c-e67d-4426-9644-4ba770272991"),
                            Company = "OpenAI Group PBC - Series C",
                            Cusip = "PPOPENAIC",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 174999811.6m,
                            Shares = 254476m,
                            Ticker = "",
                            WeightPercentage = 2.62m
                        },
                        new
                        {
                            Id = new Guid("bb30a7a7-d2e0-4fd5-a886-8e2c66fc26fe"),
                            Company = "SHOPIFY INC - CLASS A",
                            Cusip = "82509L107",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 287777320.6m,
                            Shares = 2446254m,
                            Ticker = "SHOP",
                            WeightPercentage = 4.3m
                        },
                        new
                        {
                            Id = new Guid("bc9d0d95-39bc-4cd5-a4c8-b8b96c887a31"),
                            Company = "BLOCK INC",
                            Cusip = "852234103",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 97545517.65m,
                            Shares = 1474611m,
                            Ticker = "XYZ",
                            WeightPercentage = 1.46m
                        },
                        new
                        {
                            Id = new Guid("bfd116a1-5d22-4909-869b-804f145e8df1"),
                            Company = "BEAM THERAPEUTICS INC",
                            Cusip = "07373V105",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 258016317m,
                            Shares = 8515390m,
                            Ticker = "BEAM",
                            WeightPercentage = 3.86m
                        },
                        new
                        {
                            Id = new Guid("c523aa8a-0d79-4134-b608-4de7c17e8b0a"),
                            Company = "INTELLIA THERAPEUTICS INC",
                            Cusip = "45826J105",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 139283778.8m,
                            Shares = 9423801m,
                            Ticker = "NTLA",
                            WeightPercentage = 2.08m
                        },
                        new
                        {
                            Id = new Guid("cb0ee9f8-ef36-4968-aa6d-01ac809335c9"),
                            Company = "TESLA INC",
                            Cusip = "88160R101",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 629322303.6m,
                            Shares = 1727958m,
                            Ticker = "TSLA",
                            WeightPercentage = 9.41m
                        },
                        new
                        {
                            Id = new Guid("cc33c213-4202-46e1-bbe6-922020b30bd3"),
                            Company = "RECURSION PHARMACEUTICALS-A",
                            Cusip = "75629V104",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 80398671.06m,
                            Shares = 22711489m,
                            Ticker = "RXRX",
                            WeightPercentage = 1.2m
                        },
                        new
                        {
                            Id = new Guid("d5ee4bb1-c785-4e5b-bfbd-175134577b21"),
                            Company = "TEMPUS AI INC-CL A",
                            Cusip = "88023B103",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 323875629.9m,
                            Shares = 6538979m,
                            Ticker = "TEM",
                            WeightPercentage = 4.84m
                        },
                        new
                        {
                            Id = new Guid("ed3e4a3c-644b-452e-8642-058b82ba2240"),
                            Company = "PACIFIC BIOSCIENCES OF CALIF",
                            Cusip = "69404D108",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 33098984.92m,
                            Shares = 21082156m,
                            Ticker = "PACB",
                            WeightPercentage = 0.49m
                        },
                        new
                        {
                            Id = new Guid("eda5b868-abbc-4168-ba00-14b9d67b543f"),
                            Company = "ROKU INC",
                            Cusip = "77543R102",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 268081807.7m,
                            Shares = 2516255m,
                            Ticker = "ROKU",
                            WeightPercentage = 4.01m
                        },
                        new
                        {
                            Id = new Guid("fb9c4573-e603-43de-b878-519399ca0286"),
                            Company = "BITMINE IMMERSION TECHNOLOGI",
                            Cusip = "09175A206",
                            Date = new DateOnly(2026, 4, 15),
                            Fund = "ARKK",
                            MarketValue = 137867167.6m,
                            Shares = 6418397m,
                            Ticker = "BMNR",
                            WeightPercentage = 2.06m
                        },
                        new
                        {
                            Id = new Guid("032b1743-3020-4fed-b333-c2b5e9cd4627"),
                            Company = "BULLISH",
                            Cusip = "G16910120",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 174154681.3m,
                            Shares = 4179378m,
                            Ticker = "BLSH",
                            WeightPercentage = 2.51m
                        },
                        new
                        {
                            Id = new Guid("0da43142-0312-44e6-8460-d03c7082bf1d"),
                            Company = "VERACYTE INC",
                            Cusip = "92337F107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 62749676.4m,
                            Shares = 1843410m,
                            Ticker = "VCYT",
                            WeightPercentage = 0.9m
                        },
                        new
                        {
                            Id = new Guid("109512a1-bf9c-4f5f-b78e-1f852f533ca0"),
                            Company = "CIRCLE INTERNET GROUP INC",
                            Cusip = "172573107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 302884713.5m,
                            Shares = 2870401m,
                            Ticker = "CRCL",
                            WeightPercentage = 4.36m
                        },
                        new
                        {
                            Id = new Guid("10ac21c0-3629-416a-8727-eb99844ff634"),
                            Company = "BITMINE IMMERSION TECHNOLOGI",
                            Cusip = "09175A206",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 143707523.3m,
                            Shares = 6432745m,
                            Ticker = "BMNR",
                            WeightPercentage = 2.07m
                        },
                        new
                        {
                            Id = new Guid("11860e0b-5240-4e9b-8946-4534ed055d20"),
                            Company = "CRISPR THERAPEUTICS AG",
                            Cusip = "H17182108",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 449156070m,
                            Shares = 7913250m,
                            Ticker = "CRSP",
                            WeightPercentage = 6.47m
                        },
                        new
                        {
                            Id = new Guid("1b5c2af5-dd98-4014-a581-64a552e3193f"),
                            Company = "SOFI TECHNOLOGIES INC",
                            Cusip = "83406F102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 42830452.12m,
                            Shares = 2279428m,
                            Ticker = "SOFI",
                            WeightPercentage = 0.62m
                        },
                        new
                        {
                            Id = new Guid("213e3361-4596-43e0-a241-fc2f2f505874"),
                            Company = "INTELLIA THERAPEUTICS INC",
                            Cusip = "45826J105",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 141106342.9m,
                            Shares = 9444869m,
                            Ticker = "NTLA",
                            WeightPercentage = 2.03m
                        },
                        new
                        {
                            Id = new Guid("227bf625-2cc2-4658-8a4f-9746c8d0cd57"),
                            Company = "TEMPUS AI INC-CL A",
                            Cusip = "88023B103",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 369688519.6m,
                            Shares = 6553599m,
                            Ticker = "TEM",
                            WeightPercentage = 5.32m
                        },
                        new
                        {
                            Id = new Guid("267f04f8-2e9a-4087-8b03-b7942e060c36"),
                            Company = "TWIST BIOSCIENCE CORP",
                            Cusip = "90184D100",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 204126859.2m,
                            Shares = 3542639m,
                            Ticker = "TWST",
                            WeightPercentage = 2.94m
                        },
                        new
                        {
                            Id = new Guid("32205279-d803-45eb-a088-e57722caf83d"),
                            Company = "ILLUMINA INC",
                            Cusip = "452327109",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 85080477.32m,
                            Shares = 643282m,
                            Ticker = "ILMN",
                            WeightPercentage = 1.22m
                        },
                        new
                        {
                            Id = new Guid("512b95a1-6dc3-4288-8853-a518a4a9ea03"),
                            Company = "10X GENOMICS INC-CLASS A",
                            Cusip = "88025U109",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 180183211.7m,
                            Shares = 7107819m,
                            Ticker = "TXG",
                            WeightPercentage = 2.59m
                        },
                        new
                        {
                            Id = new Guid("5bd03ed8-08c0-4251-b649-3db899c149ed"),
                            Company = "PALANTIR TECHNOLOGIES INC-A",
                            Cusip = "69608A108",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 217332708.6m,
                            Shares = 1528897m,
                            Ticker = "PLTR",
                            WeightPercentage = 3.13m
                        },
                        new
                        {
                            Id = new Guid("6088d77d-13ed-431f-a3f1-d63f159a8a01"),
                            Company = "META PLATFORMS INC-CLASS A",
                            Cusip = "30303M102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 25978729.14m,
                            Shares = 38683m,
                            Ticker = "META",
                            WeightPercentage = 0.37m
                        },
                        new
                        {
                            Id = new Guid("62745e98-7269-48c5-bc21-50d2c65fabf4"),
                            Company = "ROBLOX CORP -CLASS A",
                            Cusip = "771049103",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 225863361.7m,
                            Shares = 3777611m,
                            Ticker = "RBLX",
                            WeightPercentage = 3.25m
                        },
                        new
                        {
                            Id = new Guid("62eb5f3f-1cb3-454d-899b-1f3347510ea0"),
                            Company = "ALPHABET INC-CL C",
                            Cusip = "02079K107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 59123258.49m,
                            Shares = 176767m,
                            Ticker = "GOOG",
                            WeightPercentage = 0.85m
                        },
                        new
                        {
                            Id = new Guid("71ac8de7-0ce3-440d-b2cd-c6d391facdcc"),
                            Company = "DEERE & CO",
                            Cusip = "244199105",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 80832241.92m,
                            Shares = 140178m,
                            Ticker = "DE",
                            WeightPercentage = 1.16m
                        },
                        new
                        {
                            Id = new Guid("7b55da78-9fc2-4501-949c-0949b3835440"),
                            Company = "CERUS CORP",
                            Cusip = "157085101",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 20399832.54m,
                            Shares = 10098927m,
                            Ticker = "CERS",
                            WeightPercentage = 0.29m
                        },
                        new
                        {
                            Id = new Guid("7c2fb67a-23d7-4f3b-a63d-87fa677a2dc9"),
                            Company = "SHOPIFY INC - CLASS A",
                            Cusip = "82509L107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 312373900m,
                            Shares = 2451722m,
                            Ticker = "SHOP",
                            WeightPercentage = 4.5m
                        },
                        new
                        {
                            Id = new Guid("7f2f14df-6105-4f57-be61-9dfe2e909ccd"),
                            Company = "ADVANCED MICRO DEVICES",
                            Cusip = "7903107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 298464414.1m,
                            Shares = 1156301m,
                            Ticker = "AMD",
                            WeightPercentage = 4.3m
                        },
                        new
                        {
                            Id = new Guid("7f91c0a3-61ed-4bed-a664-5a77ba973b81"),
                            Company = "OpenAI Group PBC - Series C",
                            Cusip = "PPOPENAIC",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 174999811.6m,
                            Shares = 254476m,
                            Ticker = "",
                            WeightPercentage = 2.52m
                        },
                        new
                        {
                            Id = new Guid("8691a819-2406-4552-8fdb-bb53c64985f1"),
                            Company = "BRERA HOLDINGS PLC WTS",
                            Cusip = "BREADUMMY",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 2417103.92m,
                            Shares = 4316257m,
                            Ticker = "",
                            WeightPercentage = 0.03m
                        },
                        new
                        {
                            Id = new Guid("8b452585-90cf-4bbe-9850-28654014b99d"),
                            Company = "TAIWAN SEMICONDUCTOR-SP ADR",
                            Cusip = "874039100",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 93184967.7m,
                            Shares = 248427m,
                            Ticker = "TSM",
                            WeightPercentage = 1.34m
                        },
                        new
                        {
                            Id = new Guid("8bcab2e9-57b6-49a9-aa67-ed75d1a8a5f6"),
                            Company = "BWX TECHNOLOGIES INC",
                            Cusip = "05605H100",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 75026720.86m,
                            Shares = 314683m,
                            Ticker = "BWXT",
                            WeightPercentage = 1.08m
                        },
                        new
                        {
                            Id = new Guid("8df70514-3382-4ff2-953e-ff6beef7b617"),
                            Company = "ROKU INC",
                            Cusip = "77543R102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 275717031.1m,
                            Shares = 2521879m,
                            Ticker = "ROKU",
                            WeightPercentage = 3.97m
                        },
                        new
                        {
                            Id = new Guid("8e26f2d1-fb1e-44d4-91a5-89cca0dd1d8b"),
                            Company = "GENEDX HOLDINGS CORP",
                            Cusip = "81663L200",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 58724334.76m,
                            Shares = 870506m,
                            Ticker = "WGS",
                            WeightPercentage = 0.85m
                        },
                        new
                        {
                            Id = new Guid("900edb95-0b56-47ae-8b53-bdd5066fde68"),
                            Company = "RECURSION PHARMACEUTICALS-A",
                            Cusip = "75629V104",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 85358508.75m,
                            Shares = 22762269m,
                            Ticker = "RXRX",
                            WeightPercentage = 1.23m
                        },
                        new
                        {
                            Id = new Guid("944b74b8-be10-492e-b176-71df3627f423"),
                            Company = "FIGMA INC-CL A",
                            Cusip = "316841105",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 37364824.08m,
                            Shares = 1837012m,
                            Ticker = "",
                            WeightPercentage = 0.54m
                        },
                        new
                        {
                            Id = new Guid("954e40fe-60b1-49be-ab07-bc5dfb39eb49"),
                            Company = "AMAZON.COM INC",
                            Cusip = "23135106",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 149196169.5m,
                            Shares = 600387m,
                            Ticker = "AMZN",
                            WeightPercentage = 2.15m
                        },
                        new
                        {
                            Id = new Guid("95a97c9c-e237-409b-9387-5873a2c170e1"),
                            Company = "TESLA INC",
                            Cusip = "88160R101",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 678786065.1m,
                            Shares = 1731818m,
                            Ticker = "TSLA",
                            WeightPercentage = 9.77m
                        },
                        new
                        {
                            Id = new Guid("b2f436b3-e8d5-496e-a818-d42aa0564e91"),
                            Company = "NATERA INC",
                            Cusip = "632307104",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 80145028.61m,
                            Shares = 386819m,
                            Ticker = "NTRA",
                            WeightPercentage = 1.15m
                        },
                        new
                        {
                            Id = new Guid("b54a0bfa-49bb-405f-988d-8c12c26cc4ed"),
                            Company = "BEAM THERAPEUTICS INC",
                            Cusip = "07373V105",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 261836189.7m,
                            Shares = 8534426m,
                            Ticker = "BEAM",
                            WeightPercentage = 3.77m
                        },
                        new
                        {
                            Id = new Guid("bc17f814-5692-4942-b0de-b5f8b173f049"),
                            Company = "BROADCOM INC",
                            Cusip = "11135F101",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 75145115.52m,
                            Shares = 189416m,
                            Ticker = "AVGO",
                            WeightPercentage = 1.08m
                        },
                        new
                        {
                            Id = new Guid("bcc7cbf3-d6c8-409d-a3c5-f75163f3c5af"),
                            Company = "KRATOS DEFENSE & SECURITY",
                            Cusip = "50077B207",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 62546340.34m,
                            Shares = 837749m,
                            Ticker = "KTOS",
                            WeightPercentage = 0.9m
                        },
                        new
                        {
                            Id = new Guid("bdbe7d0e-a89f-4a3c-b895-258bf7f5d4ea"),
                            Company = "COINBASE GLOBAL INC -CLASS A",
                            Cusip = "19260Q107",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 299740908.9m,
                            Shares = 1530071m,
                            Ticker = "COIN",
                            WeightPercentage = 4.32m
                        },
                        new
                        {
                            Id = new Guid("be955f9d-12c9-44aa-b16f-5f5209de9dbe"),
                            Company = "BLOCK INC",
                            Cusip = "852234103",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 100453338.8m,
                            Shares = 1477907m,
                            Ticker = "XYZ",
                            WeightPercentage = 1.45m
                        },
                        new
                        {
                            Id = new Guid("c2295709-5773-4989-879e-29726ecedb11"),
                            Company = "ALIBABA GROUP HOLDING-SP ADR",
                            Cusip = "01609W102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 63020648.32m,
                            Shares = 472844m,
                            Ticker = "BABA",
                            WeightPercentage = 0.91m
                        },
                        new
                        {
                            Id = new Guid("cc64203c-8d34-446a-98b2-7a70c7506901"),
                            Company = "TERADYNE INC",
                            Cusip = "880770102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 140960690.6m,
                            Shares = 386236m,
                            Ticker = "TER",
                            WeightPercentage = 2.03m
                        },
                        new
                        {
                            Id = new Guid("d4aa97e4-6016-42a2-acf7-d63ad5dabae6"),
                            Company = "BRERA HOLDINGS PLC-CL B",
                            Cusip = "G13311116",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 5733071.32m,
                            Shares = 6666362m,
                            Ticker = "SLMT",
                            WeightPercentage = 0.08m
                        },
                        new
                        {
                            Id = new Guid("e149a541-ba89-41ff-97a6-0bbf40132ff6"),
                            Company = "COREWEAVE INC-CL A",
                            Cusip = "21873S108",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 189855455.8m,
                            Shares = 1599591m,
                            Ticker = "CRWV",
                            WeightPercentage = 2.73m
                        },
                        new
                        {
                            Id = new Guid("f485d50a-762e-4d2b-98d1-10dd36a3c5d9"),
                            Company = "ROBINHOOD MARKETS INC - A",
                            Cusip = "770700102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 337972147.3m,
                            Shares = 3870501m,
                            Ticker = "HOOD",
                            WeightPercentage = 4.87m
                        },
                        new
                        {
                            Id = new Guid("f4cb92ba-c628-4576-a6a0-30bd5e779bcb"),
                            Company = "BAIDU INC - SPON ADR",
                            Cusip = "56752108",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 67157377.3m,
                            Shares = 555295m,
                            Ticker = "BIDU",
                            WeightPercentage = 0.97m
                        },
                        new
                        {
                            Id = new Guid("f5f57c97-de7e-464b-b8c3-145b949edcba"),
                            Company = "NVIDIA CORP",
                            Cusip = "67066G104",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 80348849.49m,
                            Shares = 404027m,
                            Ticker = "NVDA",
                            WeightPercentage = 1.16m
                        },
                        new
                        {
                            Id = new Guid("f739e1ca-706f-402a-970f-da7ad06b2c75"),
                            Company = "PACIFIC BIOSCIENCES OF CALIF",
                            Cusip = "69404D108",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 33806867.2m,
                            Shares = 21129292m,
                            Ticker = "PACB",
                            WeightPercentage = 0.49m
                        },
                        new
                        {
                            Id = new Guid("fac54e9a-b2a1-47cd-b56e-534444c3e169"),
                            Company = "GOLDMAN FS TRSY OBLIG INST 468",
                            Cusip = "X9USDGSFT",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 9419424.62m,
                            Shares = 9419425m,
                            Ticker = "",
                            WeightPercentage = 0.14m
                        },
                        new
                        {
                            Id = new Guid("fcfcaadc-680a-4010-ad61-de339bd88ad8"),
                            Company = "ARCHER AVIATION INC-A",
                            Cusip = "03945R102",
                            Date = new DateOnly(2026, 4, 16),
                            Fund = "ARKK",
                            MarketValue = 111350603.2m,
                            Shares = 18374687m,
                            Ticker = "ACHR",
                            WeightPercentage = 1.6m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
