// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PV260.ArkFundsTracker.Web.Infrastructure.Data;

#nullable disable

namespace PV260.ArkFundsTracker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416171917_AddIdToFundPosition")]
    partial class AddIdToFundPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PV260.ArkFundsTracker.Web.Slices.FundPosition.FundPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cusip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fund")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ARKK");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Shares")
                        .HasColumnType("numeric");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("idx_fund_positions_ticker");

                    b.ToTable("fund_positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_fund_positions_fund", "\"Fund\" = 'ARKK'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
